name: offertelavoroflutter_it_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #utilities
  logger: ^1.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  pine: ^1.0.2
  auto_route: ^5.0.4
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.20
  provider: ^6.0.5
  http: ^0.13.5

  #theme selector utilitie
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.14

  #UI/UX
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
